### PR TITLE
Updated discussion areas for README for CIPs

### PR DESCRIPTION
**Pull request by davestaxcp**
Since the Counterparty Slack chat is not used (to my knowledge it is inaccessible), it should be removed and then replaced with the places developers and users still go to which is:

The Counterparty Forums
The CIP Discussions in github
The Counterparty Telegram
The Counterparty Developer Telegram

### CODE REVIEW

**Comment by jdogresorg** [comment]
Perhaps remove "The Counterparty Forums" from this list, as I think we want to migrate most dev conversations to github discussions so they can be documented there instead of on the forums.

**Comment by jotapea** [comment]
I think we should remove all except the "The discussions in github". See https://github.com/CounterpartyXCP/cips/discussions/97.

**Comment by jdogresorg** [comment]
Except for the fact that 90% of the dev conversations happen on telegram…. Not GitHub.Sent from my iPhoneOn Sep 15, 2023, at 2:25 PM, Juan Alemán ***@***.***> wrote:﻿
I think we should remove all except the "The discussions in github". See #97.

**Comment by jdogresorg** [comment]
Except for the fact that 90% of the Counterparty dev conversations happen on telegram…. Not GitHub. 

IMO we want to push people towards github and away from using the forums. However, we don't want to remove telegram, where most of the dev conversations happen. Some prefer to interact via github, but most prefer to chat via telegram, and slack before telegram.

**Comment by davestaxcp** [comment]
Added a second commit as per @jdogresorg 's comments

Also @jotapea , as Jdog mentioned, there are many vibrant and informative discussions that happen between the active developers and interested users in the Counterparty Dev Telegram... It is laid out here that the main discussion and documentation should always be posted in the Counterparty CIP Discussions Github, but the main other place at the moment that developers are discussing upgrades is in the Counterparty Dev Telegram and I suggest you join it and be apart of the conversation there.

Also I did not use the word "official" at all in this commit as per #97 .

**Comment by jotapea** [comment]
See: https://github.com/CounterpartyXCP/cips/discussions/97#discussioncomment-7491604

Based on what I mentioned there, then the specific suggestions I have for this PR are:

- Be specific that the main official place for per topic conversations is the CIP Discussions (https://github.com/CounterpartyXCP/cips/discussions)
- Then, there are multiple non-official development focused chats, including:
  - https://t.me/Counterparty_Dev
  - https://t.me/xcpdev
  - (there are others, but they should decide themselves if they want to be added here)

**Pull request closed without merging**
